In [12]:
# mathematical funtion 

# now learning about aggregate funtion

    import numpy as np
    arr = np.array([1,2,3,4,5])
    print (np.sum(arr))
    print (np.prod(arr))
    print (np.min(arr))
    print (np.max(arr))
    print (np.argmin(arr))
    print (np.argmax(arr))
    
    print (np.mean(arr))
    print (np.std(arr))
    print (np.median(arr))
    print (np.var(arr)) # this is about varience


15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [1]:
import numpy as np
# this are the power functions
arr = np.array([1,2,3,4,5])
print (np.square(arr))
print (np.sqrt(arr))
print (np.pow(arr,3))
print ( np.log(arr))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [17]:
# rounding function
print (np.round(3.4))   #les then 0.5 will round down and visa versa
print (np.ceil(3.0001))     #round up 
print (np.floor(3.9)) # round down
print (np.trunc(3.980900))

arr = np.array([1,2,9,8,3,4,5,5,5,5,5])
print(np.unique(arr)) #will give the values which are not repeated
print(np.sort(arr))


arr1 = np.array([-1,2,9,8,-3,-4,5,-5,-5,-5,5])
print (np.abs(arr1))

3.0
4.0
3.0
3.0
[1 2 3 4 5 8 9]
[1 2 3 4 5 5 5 5 5 8 9]
[1 2 9 8 3 4 5 5 5 5 5]
