In [10]:
import numpy as np

array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (array2d)
print(np.sum(array2d))

column_sum = np.sum(array2d, axis = 0)
print(column_sum)


row_sum = np.sum(array2d, axis = 1)
print(row_sum)

print (array2d [0:3,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]
 [8]]


In [27]:
import numpy as np

# 3d array
arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3d, arr3d.shape)
print(arr3d[0,1,1])
print(arr3d[0,1,0])
print(arr3d[1,1,0])
print(arr3d[1,2,1])

# slicing
print(arr3d[:,0,:])   #first row
print(arr3d[:,:,0])   #first column


arr3d[:,0,:] = 89
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
3
9
12
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[89 89]
  [ 3  4]
  [ 5  6]]

 [[89 89]
  [ 9 10]
  [11 12]]]
