In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.array([1,2,3,4,5,6,7,8])

# print( arr **2)
print (arr + arr1)
print (arr + 10 ) 



[ 2  4  6  8 10 12 14 16]
[11 12 13 14 15 16 17 18]


In [2]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
print ( arr + arr2)


[[ 2  4  6  8 10 12 14 16]
 [ 2  4  6  8 10 12 14 16]]


In [8]:
import numpy as np 
# going to learn about the normalization
arr = ( [[1,2],[3,4]])
mean = np.mean (arr)
sandard = np.std(arr)
# print (mean )
# print (sandard)

normalized_arr =((arr-mean)/sandard)
print (normalized_arr)
print (sandard)
print (np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
1.118033988749895
1.118033988749895
